### ISSUE TITLE
non-ASCII characters missing from PDF export

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [OPIDoR/DMPOPIDoR#111]
**Expected behaviour:**
I would expect non-ASCII characters to be visible in the footer of exported PDF files as:
```
Créé avec DMP OPIDoR. Dernière modification 
```

**Actual behaviour:**
Instead non-ASCII characters seem to be missing from the footer of exported PDF files, at least in the Google Chrome integrated PDF viewer:
```
Cr avec DMP OPIDoR. Dernire modification 
```
By the way, not sure why the footer is in French - the document is written in English.

**Steps to reproduce:**
Create a project and export it as PDF. Might require a web browser specifying French as the default language.

**Comment by DimitriPapadopoulos** [comment]
Perhaps add [`<%# coding: UTF-8 %>` in the ERB template](https://stackoverflow.com/questions/9695662/how-to-use-utf-8-encoded-data-in-erb-template#54393216)?

**Comment by benjaminfaure** [comment]
Thank you for your feedback @DimitriPapadopoulos .
This is a known issue.

The footer of the pdf export is not rendered with the content, it comes from the controller here : 
https://github.com/OPIDoR/DMPOPIDoR/blob/d8ad55319880f2f8a7732b28e3d28a92cfe4bada/app/controllers/plans_controller.rb#L310-L314

As you can see, the encoding is already set to UTF-8, but it doesn't seem to work. It should be resolved in the next version, I did some changes on the operating system running DMP OPIDoR, and the problem seems to be resolved, strangely ... (I'll close this issue when we deploy on our production server)

As fot your last question, the footer language is rendered accordingly to the application language.

**Comment by DimitriPapadopoulos** [comment]
Ah, great news, thank you. If you don't mind, how is the _application language_ defined? Can I set it to English and how?

**Comment by benjaminfaure** [comment]
You can change it in the application menu next to the user profile (and logout link). It's set to French by default. 
The default value can be changed in you user profile, if you'd like to automatically change to English once you're logged in :)

**Comment by benjaminfaure** [comment]
Hello,
The issue should be now be resolved on the production server.
